spring:
  application:
    name: springdatajpa-crud

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  flyway:
    enabled: true
    locations: classpath:db/migration
