services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  app:
    build: .
    container_name: springdatajpa-crud
    environment:
      JAVA_TOOL_OPTIONS: -Xmx512m -Xms256m
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  app-network: